/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.4.0" // need this for generating .jar
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("net.dv8tion:JDA:6.3.2") {
        exclude(module = "opus-java") // for audio stuff dont need this
        exclude(module = "tink") // for encrypting and decrypting audio, dont need this
    }
    implementation("ch.qos.logback:logback-classic:1.5.32") // needed for logging (https://jda.wiki/setup/logging/)
    compileOnly("org.projectlombok:lombok:1.18.44") // lombok = less boilerplate code
    annotationProcessor("org.projectlombok:lombok:1.18.44") // lombok = less boilerplate code

    testCompileOnly("org.projectlombok:lombok:1.18.44") // lombok = less boilerplate code
    testAnnotationProcessor("org.projectlombok:lombok:1.18.44") // lombok = less boilerplate code
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "va.rembot.Bot"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
