# https://docs.github.com/en/actions/tutorials/build-and-test-code/java-with-gradle
# This is to catch any errors before merging (if code doesn't build)
name: Build code on PR into main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3

      - name: Setup JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 #v5.7.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb #v6.3.0

      - name: Build with Gradle
        run: ./gradlew shadowJar
